// leave off @2x/@3x
const images = {
  logo: require("../Images/ir.png"),
  clearLogo: require("../Images/top_logo.png"),
  launch: require("../Images/launch-icon.png"),
  ready: require("../Images/your-app.png"),
  ignite: require("../Images/ignite_logo.png"),
  igniteClear: require("../Images/ignite-logo-transparent.png"),
  tileBg: require("../Images/tile_bg.png"),
  background: require("../Images/BG.jpg"),
  buttonBackground: require("../Images/button-bg.png"),
  api: require("../Images/Icons/icon-api-testing.png"),
  components: require("../Images/Icons/icon-components.png"),
  deviceInfo: require("../Images/Icons/icon-device-information.png"),
  faq: require("../Images/Icons/faq-icon.png"),
  home: require("../Images/Icons/icon-home.png"),
  theme: require("../Images/Icons/icon-theme.png"),
  usageExamples: require("../Images/Icons/icon-usage-examples.png"),
  chevronRight: require("../Images/Icons/chevron-right.png"),
  hamburger: require("../Images/Icons/hamburger.png"),
  backButton: require("../Images/Icons/back-button.png"),
  closeButton: require("../Images/Icons/close-button.png"),
  addExperience: require("../Images/add_experience.png"),
  dpPlaceholder: require("./assets/images/dp_placeholder.png"),
  backArrow: require("./assets/images/back_ic.png"),
  ArrowDown: require("./assets/images/chevron_down.png"),
  UrgentJobs: require("./assets/images/urgent_jobs_ic.png"),
  ApprovedJobs: require("./assets/images/approved_job_ic.png"),
  OneDayShift: require("./assets/images/one_day_shift_ic.png"),
  SameDayShipt: require("./assets/images/same_day_shift.png"),
  SubmitTimesheet: require("./assets/images/submit_timesheet_ic.png"),
  ApprovedTimesheet: require("./assets/images/approved_timesheet_ic.png"),
  clockRed: require("./assets/images/clock_red.png"),
  calendarRed: require("./assets/images/calendar_red.png"),
  clockBlue: require("./assets/images/clock_blue.png"),
  calendarBlue: require("./assets/images/calendar_blue.png"),
  clockGreen: require("./assets/images/clock_green.png"),
  calendarGreen: require("./assets/images/calendar_green.png"),
  jobFilter: require("./assets/images/filter_ic.png"),
  editbasicinfo: require("./assets/images/edit_info_ic.png"),
  checkMark: require("../Images/Icons/check.png"),
  camera: require("../Images/Icons/camera.png"),
  uploadImage: require("../Images/Icons/upload_image.png"),
  calendarWhite: require("../Images/Icons/calendar-white.png"),
  loginLogo: require("../Images/login_logo.png"),
  noDataTransparent: require("../Images/norecordtrans.png"),
  noData: require("../Images/norecord.png"),
  noDataNoText: require("../Images/norecordnotext.png"),
  infoLogo: require("../Images/Icons/info.png"),
};

export default images;
